id: 87a9634ac8e246f8b4468df3184a83d9
initial_creation_type: ebook
source_metadata:
  title: ༄༅། །བྱང་ཆུབ་སེམས་དཔའི་ཚུལ་ཁྲིམས་ཀྱི་རྣམ་བཤད་བྱང་ཆུབ་གཞུང་ལམ་བཞུགས་སོ།།
  subtitle: ''
  authors:
  - རྗེ་བཙུན་ཙོང་ཁ་པ་བློ་བཟང་གྲགས་པ།
  collection: Tsadra Geluk Series
  publisher: Tsadra Publishing
  id: TSD-GS-04
  cover: tmp64c2ao9q.JPG
  credit: tmppnhjoa_t.jpg
